/* ==========================================================================
   ui-desk.js — support desk, operations center, finance, admin
   ========================================================================== */
function deskFrame(role, views, main, o = {}) {
  const nav = S.nav[role];
  return `<div class="desk" data-role="${role}"><aside class="desk-nav" aria-label="${attr(L('أقسام', 'Sections'))}"><div class="desk-brand"><span class="wordmark wordmark-xs">${L('وصّلي', 'Wasaly')}</span><small>${L(ROLE_META[role].ar, ROLE_META[role].en)}</small></div>${views.map((v) => `<button type="button" class="${cls('desk-tab', nav.view === v.id && 'on')}" data-act="desk-view" data-role="${role}" data-v="${v.id}" ${nav.view === v.id ? 'aria-current="page"' : ''}>${ic(v.icon, 18)}<span>${v.label}</span>${v.badge ? `<span class="count">${v.badge}</span>` : ''}</button>`).join('')}<div class="desk-who">${ic('user-round', 16)}<span>${esc(o.who || '')}</span></div></aside><div class="desk-main" tabindex="0" role="region" aria-label="${attr(L(ROLE_META[role].ar, ROLE_META[role].en))}">${S.sys.outage && role === 'ops' ? banner('danger', 'server-crash', L('وضع الطوارئ: المنظومة واقفة. كل حاجة بالتليفون، وكل خطوة تتسجل يدوي.', 'Emergency mode: system down. Everything by phone, logged manually.'), btn(L('رجّع الخدمة', 'Restore service'), 'ops-restore', { kind: 'secondary', size: 'sm' })) : ''}${main}</div></div>`;
}
const deskHead = (title, sub, actions = '') => `<header class="desk-head"><div><h1>${title}</h1>${sub ? `<p>${sub}</p>` : ''}</div><div class="desk-actions">${actions}</div></header>`;
const prioChip = (p) => `<span class="pill pill-${PRIO[p][2]}">${L(PRIO[p][0], PRIO[p][1])}</span>`;

/* ================================================================== SUPPORT */
function supportDesk() {
  const all = Object.values(S.tickets).sort((a, b) => (a.status === 'resolved' || a.status === 'closed') - (b.status === 'resolved' || b.status === 'closed') || ['now', 'today', 'next', 'routine'].indexOf(a.prio) - ['now', 'today', 'next', 'routine'].indexOf(b.prio) || b.at - a.at);
  const open = all.filter((t) => !['resolved', 'closed'].includes(t.status));
  const views = [{ id: 'tickets', icon: 'ticket', label: L('التذاكر', 'Tickets'), badge: open.length || '' }, { id: 'templates', icon: 'messages-square', label: L('قوالب الرسائل', 'Message templates') }, { id: 'rules', icon: 'book-open', label: L('قواعد الدعم', 'Support rules') }];
  const v = S.nav.support.view; let main = '';
  if (v === 'tickets') {
    const sel = S.nav.support.sel && S.tickets[S.nav.support.sel];
    main = `${deskHead(L('طابور الشكاوى', 'Ticket queue'), L('الأولوية بالأثر، مش بعلو صوت الشاكي.', 'Priority by impact, not by how loud the complaint is.'))}${AA('s-priority-by-impact', 's-first-response')}
      <div class="${cls('split', sel && 'has-sel')}"><div class="split-list">${all.length ? all.map((t) => `<button type="button" class="${cls('tk-row', sel && sel.id === t.id && 'on')}" data-act="s-open" data-id="${t.id}">${prioChip(t.prio)}<div class="tk-main"><b>${t.id} · ${ticketKindLabel(t.kind)}</b><small>${t.orderId ? `<bdi dir="ltr">${t.orderId}</bdi> · ` : ''}${ticketStatusLabel(t.status)} · ${clockStr(t.at)}</small></div>${t.queue === 'ops' ? `<span class="dotchip tone-info">${L('عمليات', 'Ops')}</span>` : ''}</button>`).join('') : empty(`<div class="big-ic">${ic('ticket', 40)}</div>`, L('مفيش تذاكر', 'No tickets'), L('اعمل شكوى من تطبيق العميل أو احقن مشكلة.', 'Create one from the customer app or inject a problem.'))}</div>
      <div class="split-detail">${sel ? `<div class="split-back">${btn(L('رجوع للطابور', 'Back to queue'), 's-close', { kind: 'ghost', size: 'sm', icon: 'arrow-right', cls: 'ic-back-btn' })}</div>${ticketDetail(sel)}` : `<div class="calm-center">${ic('mouse-pointer-2', 28)}<p>${L('اختار تذكرة', 'Select a ticket')}</p></div>`}</div></div>`;
  } else if (v === 'templates') {
    main = `${deskHead(L('مكتبة الرسائل', 'Message library'), L('39 قالب من الدليل — القالب نقطة بداية مش نص مقدّس.', '39 templates from the manual.'))}${truth('draft')} ${truth('notbuilt', { label: L('مش موجودة في التطبيق', 'Not in the app') })}${AA('s-templates')}
      <div class="tpl-grid">${Object.values(MANUAL.msgs).map((m) => `<article class="card tpl"><span class="msgq-id">${m.id}</span><b>${esc(m.situation)}</b><p>${esc(m.written)}</p>${m.note ? `<small>${esc(m.note)}</small>` : ''}</article>`).join('')}</div>`;
  } else {
    main = `${deskHead(L('قواعد الدعم', 'Support rules'), '')}<div class="stack-12">${['علاج صاحب الشكوى ما بيستناش معرفة المسؤول.', 'الشكوى المقفولة بصمت مش شكوى اتحلّت — ردّ مسبّب دايمًا.', 'ممنوع «تم الاسترداد» قبل ما الفلوس توصل.', 'ممنوع «النظام رفض» — كل قرار بشري وليه اسم.', 'اللي بيراجع التظلّم مش هو اللي قرر — ولو مفيش غيره، يتقال للعميل.', 'سبب الرفض ممكن يكشف ظرف صحي أو عائلي — بيتسجل بالحد الأدنى وما يتشاركش.'].map((r) => `<div class="rule">${ic('check', 16)}<span>${r}</span></div>`).join('')}${AA('s-remedy-first', 's-privacy-reason', 's-support-coverage')}<div class="chips-row">${P('SUP_001')}${P('SUP_003')}${P('SUP_004')}${P('SUP_005')}${P('CUSTOMER_008')}</div></div>`;
  }
  return deskFrame('support', views, main, { who: L(`${PEOPLE.support.name} — خدمة العملاء`, 'Sara — Support') });
}
function recommendedFor(t) {
  const map = { missing: 'INC-0013', wrong: 'INC-0014', damaged: 'INC-0014', food_safety: 'INC-0015', cannot_deliver: 'INC-0001', safety: 'INC-0049', payment: 'INC-0016', cash_diff: 'INC-0032', late: 'INC-0011', captain: 'INC-0034' };
  return MANUAL.inc[map[t.kind]];
}
function evidenceTable(o) {
  const rows = [
    [L('سجل الانتقالات', 'Transitions log'), true, L('أقوى دليل متاح', 'Strongest evidence available')],
    [L('سجل محاولات الاتصال', 'Call attempts'), 'partial', L('بيثبت إن محاولة حصلت — مش إن العميل تعمّد', 'Proves an attempt, not intent')],
    [L('موقع الكابتن وتوقيته', 'Captain location & time'), true, L('بيثبت إنه كان هناك — مش إنه خبّط', 'Proves presence, not knocking')],
    [L('مدة الانتظار', 'Wait duration'), false, '—'], [L('سبب الرفض بنص العميل', 'Refusal reason verbatim'), !!(o && o.cnd && o.cnd.words), L('بيثبت اللي اتقال — مش صدقه', 'What was said, not its truth')],
    [L('صورة الموقع', 'Location photo'), false, '—'], [L('إثبات استلام من التاجر', 'Pickup proof'), false, '—'], [L('سجل مصير البضاعة', 'Goods-fate record'), false, '—'],
  ];
  return `<table class="tbl"><thead><tr><th>${L('الدليل', 'Evidence')}</th><th>${L('متاح؟', 'Available?')}</th><th>${L('حدوده', 'Limits')}</th></tr></thead><tbody>${rows.map((r) => `<tr><td>${r[0]}</td><td>${r[1] === true ? `<span class="ok-t">${ic('check', 14)}${L('نعم', 'Yes')}</span>` : r[1] === 'partial' ? `<span class="warn-t">${L('جزئيًا', 'Partly')}</span>` : `<span class="err-t">${ic('x', 14)}${L('لا', 'No')}</span>`}</td><td class="muted">${r[2]}</td></tr>`).join('')}</tbody></table>`;
}
function ticketDetail(t) {
  const o = t.orderId ? ord(t.orderId) : null; const rec = recommendedFor(t);
  const line = o && (o.lines.find((l) => l.pid === t.item) || o.lines[0]);
  const refundAmt = o ? (t.kind === 'missing' ? line.unit : ['wrong', 'damaged'].includes(t.kind) ? line.unit * line.qty : t.kind === 'food_safety' ? o.total : 0) : (S.ghostCharge ? S.ghostCharge.amount : 0);
  const rf = o && o.refund;
  const tpl = { missing: 'MSG-C-009', wrong: 'MSG-C-009', damaged: 'MSG-C-009', food_safety: 'MSG-C-012', cannot_deliver: 'MSG-C-004', payment: 'MSG-C-008', late: 'MSG-C-002', cash_diff: 'MSG-C-007' }[t.kind];
  return `<article class="tk-detail stack-16">
    <header class="row-between"><div><h2>${t.id} · ${ticketKindLabel(t.kind)}</h2><p class="muted">${t.orderId ? `<bdi dir="ltr">${t.orderId}</bdi> · ` : ''}${L('من', 'by')} ${actorLabel(t.by)} · ${clockStr(t.at)}</p></div><div class="stack-8 end">${prioChip(t.prio)}<span class="pill">${ticketStatusLabel(t.status)}</span></div></header>
    ${o ? `<section class="card">${sectionHead(L('سياق الطلب', 'Order context'), { icon: 'receipt-text' })}<div class="kv"><span>${L('المتجر', 'Store')}</span><b>${esc(mName(o.mid))}</b><span>${L('الكابتن', 'Captain')}</span><b>${esc(kName(o.kid) || '—')}</b><span>${L('الحالة', 'Status')}</span><b>${stPill(o.st)}</b><span>${L('الدفع', 'Payment')}</span><b>${payLabel(o.pay.method)} · ${money(o.total)}</b><span>${L('المستلم', 'Recipient')}</span><b>${o.rcp.mode === 'other' ? esc(o.rcp.name) : L('العميل نفسه', 'The customer')}</b></div>
      <details class="mt-8"><summary>${L('سجل الانتقالات', 'Transitions log')}</summary>${tlList(o, 'support')}</details></section>` : ''}
    ${rec ? `<section class="card rec">${sectionHead(L('الإجراء الموصى به', 'Recommended action'), { icon: 'list-checks', aside: `<span class="msgq-id">${rec.id}</span>` })}<p><b>${L('فورًا:', 'Now:')}</b> ${esc(rec.action)}</p><p><b>${L('علاج العميل:', 'Customer remedy:')}</b> ${esc(rec.remedy)}</p>${rec.tempFund ? `<p class="muted"><b>${L('التمويل المؤقت:', 'Temporary funding:')}</b> ${esc(rec.tempFund)} · <b>${L('التحميل النهائي:', 'Final loading:')}</b> ${esc(rec.final)}</p>` : ''}${truth('draft')}</section>` : ''}
    ${t.kind === 'cannot_deliver' && o ? `<section class="card">${sectionHead(L('الأدلة — وإيه اللي ما بتثبتوش', 'Evidence — and what it does not prove'), { icon: 'file-search' })}${evidenceTable(o)}${AA('s-evidence-gaps')}</section>` : ''}
    ${refundAmt ? `<section class="card stack-12">${sectionHead(L('الاسترداد (4 مراحل)', 'Refund (4 stages)'), { icon: 'hand-coins' })}
      ${!rf ? `<p>${L('المبلغ المقترح:', 'Suggested amount:')} <b class="num">${money(refundAmt)}</b> ${t.kind === 'missing' ? L('— قيمة الصنف الناقص', '— missing item value') : ''}</p>${btn(L('اطلب الاسترداد', 'Request refund'), 's-refund-req', { data: { id: t.id, amt: refundAmt } })}${AA('s-remedy-first')}`
        : `<ol class="stages">${['requested', 'approved', 'executed', 'confirmed'].map((s, i) => `<li class="${['requested', 'approved', 'executed', 'confirmed'].indexOf(rf.stage) >= i ? 'done' : ''}">${{ requested: L('مطلوب', 'Requested'), approved: L('معتمد', 'Approved'), executed: L('منفّذ', 'Executed'), confirmed: L('وصل', 'Received') }[s]}</li>`).join('')}</ol>
        ${rf.stage === 'requested' ? `${banner('warning', 'scale', L('حد صلاحية الاسترداد مش محدد (PAR-0004) → المؤسس يعتمد كل استرداد. والاعتماد فوق الحد محظور لحد ما يبقى فيه شخص تاني (AUT-0004).', 'No refund limit set → the founder approves every refund.'))}<div class="stack-8">${truth('sim', { label: L('الموافقة هنا تمثيل للخطوة — مش موافقة حقيقية', 'This approval is a simulated step — not a real one') })}${btn(L('محاكاة: المؤسس يوافق على الاسترداد', 'Simulate: founder approves the refund'), 's-refund-approve', { data: { id: t.id }, icon: 'flask-conical' })}</div>${AA('c-refund-authority')}` : ''}
        ${rf.stage === 'approved' ? `<p>${L('اختار طريقة الرد:', 'Choose the refund route:')}</p><div class="grid-2">${btn(o && o.pay.method === 'cash' ? L('نقدًا (حسب السياسة)', 'Cash (policy)') : L('نفس وسيلة الدفع', 'Same method'), 's-refund-exec', { data: { id: t.id, route: o && o.pay.method === 'cash' ? 'cash' : 'same' } })}${o && o.pay.method === 'cash' ? btn(L('قسيمة رصيد (سلوك الكود الحالي)', 'Voucher (current code)'), 's-refund-exec', { kind: 'secondary', data: { id: t.id, route: 'voucher' } }) : ''}</div>${o && o.pay.method === 'cash' ? `${note(L('صرف كاش للعميل: مفيش مسار مبني في النظام — لازم يتعمل يدوي (مع كابتن أو في المكتب).', 'Paying cash back has no built path — manual.'), { icon: 'construction' })}${AA('s-refund-route-conflict')}` : ''}` : ''}
        ${rf.stage === 'executed' ? `${btn(L('العميل استلم فعلًا', 'Customer actually received it'), 's-refund-confirm', { data: { id: t.id } })}${note(L('لحد هنا ممنوع نقول «تم».', 'Never say “done” before this.'))}` : ''}
        ${rf.stage === 'confirmed' ? `<p class="ok">${ic('circle-check', 14)}${L('وصل للعميل', 'Received by the customer')} ${routeLabel(rf.route)}</p>` : ''}`}</section>` : ''}
    ${tpl ? `<section class="card stack-8">${sectionHead(L('رسالة للعميل', 'Message to the customer'), { icon: 'message-circle' })}${msgQuote(tpl)}${btn(L('ابعت الرسالة', 'Send message'), 's-send-tpl', { kind: 'secondary', data: { id: t.id, tpl } })}</section>` : ''}
    <section class="card stack-8">${sectionHead(L('المحادثة والملاحظات', 'Conversation & notes'), { icon: 'messages-square' })}${t.log.map((x) => `<div class="bubble ${x.who === 'support' ? 'me' : ''} ${x.kind === 'note' ? 'note-b' : ''}"><small class="who">${actorLabel(x.who)}${x.kind === 'note' ? ' · ' + L('ملاحظة داخلية', 'internal note') : ''}</small><p>${esc(x.text)}</p><small>${clockStr(x.t)}</small></div>`).join('')}
      <div class="chat-in"><label class="sr-only" for="snote">${L('ملاحظة', 'Note')}</label><input id="snote" class="input" data-bind="s-note" value="${attr(S.nav.support.note || '')}" placeholder="${attr(L('ملاحظة داخلية أو رد…', 'Internal note or reply…'))}" autocomplete="off">${iconBtn('sticky-note', L('ملاحظة داخلية', 'Internal note'), 's-add-note', { data: { id: t.id } })}${iconBtn('send', L('رد على العميل', 'Reply to customer'), 's-reply', { data: { id: t.id } })}</div></section>
    <section class="card stack-8">${sectionHead(L('القرار', 'Decision'), { icon: 'gavel' })}
      <div class="grid-2">${btn(L('تحقيق', 'Investigate'), 's-status', { kind: 'secondary', data: { id: t.id, v: 'investigating' } })}${btn(L('مستني معلومة', 'Awaiting info'), 's-status', { kind: 'secondary', data: { id: t.id, v: 'awaiting' } })}${btn(L('اتحلّت — بسبب مكتوب', 'Resolve with reason'), 's-status', { data: { id: t.id, v: 'resolved' } })}${btn(L('صعّد للمؤسس', 'Escalate to founder'), 's-escalate', { kind: 'ghost', data: { id: t.id } })}</div>
      ${t.status === 'appeal' ? `${banner('warning', 'scale', L('تظلّم: لازم يراجعه حد غير اللي قرر. الفريق النهارده شخص أو اتنين — لو مفيش، سجّل التعذّر وقول للعميل صراحةً.', 'Appeal: must be reviewed by someone else.'))}${AA('s-independent-review')}` : ''}
    </section>
    <div class="chips-row">${P('SUP_004')}${P('CUSTOMER_004')}${P('FIN_002')}</div>
  </article>`;
}
onAct('s-open', (d) => { S.nav.support.sel = d.id; const t = S.tickets[d.id]; if (t.status === 'open') { t.status = 'investigating'; ticketLog(t, 'support', L('الدعم فتح التذكرة', 'Support opened the ticket'), 'status'); } requestRender(); });
onAct('bind:s-note', (v) => { S.nav.support.note = v; });
onAct('s-add-note', (d) => { const v = (S.nav.support.note || '').trim(); if (!v) return; ticketLog(S.tickets[d.id], 'support', v, 'note'); S.nav.support.note = ''; requestRender(); });
onAct('s-reply', (d) => { const v = (S.nav.support.note || '').trim(); if (!v) return; ticketLog(S.tickets[d.id], 'support', v, 'msg'); S.nav.support.note = ''; notify('customer', { title: L('رد جديد من خدمة العملاء', 'New reply from support'), body: v, icon: 'messages-square', silent: userRole() !== 'customer' }); requestRender(); });
onAct('s-send-tpl', (d) => { const m = MANUAL.msgs[d.tpl]; const t = S.tickets[d.id]; const o = t.orderId && ord(t.orderId); const txt = m.written.replace('{{ORDER_ID}}', o ? o.id : '').replace('{{AMOUNT}}', o && o.refund ? money(o.refund.amount) : '').replace('{{REFUND_ROUTE}}', o && o.refund && o.refund.route ? routeLabel(o.refund.route) : L('نفس طريقة الدفع', 'the same method')).replace('{{ITEM}}', o && t.item ? pName(t.item) : '').replace(/\{\{[A-Z_]+\}\}/g, '…'); ticketLog(t, 'support', txt, 'msg'); notify('customer', { title: L('رسالة من خدمة العملاء', 'Message from support'), body: txt, icon: 'messages-square', silent: userRole() !== 'customer' }); toast(L('اتبعتت — القالب نقطة بداية، راجعه قبل الإرسال في الحقيقة', 'Sent — review templates before sending in reality'), 'success', 'send'); requestRender(); });
onAct('s-refund-req', (d) => { const t = S.tickets[d.id]; const o = ord(t.orderId); if (!o) { toast(L('مفيش طلب مرتبط — راجع سجل الدفع الأول (INC-0016)', 'No linked order — check the payment record first'), 'warning', 'file-search'); requestRender(); return; } refundRequest(o, +d.amt, ticketKindLabel(t.kind), 'support'); ticketLog(t, 'support', L(`اتطلب استرداد ${money(+d.amt)}`, `Refund requested ${money(+d.amt)}`), 'status'); requestRender(); });
onAct('s-refund-approve', (d) => { const t = S.tickets[d.id]; const o = ord(t.orderId); refundApprove(o, 'founder'); ticketLog(t, 'founder', L('خطوة محاكاة: موافقة المؤسس على الاسترداد (في المسودة المؤسس بيوافق على كل استرداد لحد ما يتحدد حد — PAR-0004)', 'Simulated step: founder approval of the refund'), 'status'); audit('founder', 'refund.approve', `${o.id} ${money(o.refund.amount)}`); requestRender(); });
onAct('s-refund-exec', (d) => { const t = S.tickets[d.id]; const o = ord(t.orderId); refundExecute(o, d.route); ticketLog(t, 'finance', L(`اتنفّذ ${routeLabel(d.route)}`, `Executed ${routeLabel(d.route)}`), 'status'); if (d.route === 'voucher') toast(L('قسيمة = رصيد → سؤال البنك المركزي (VAL-0008) ومخالفة القاعدة 12-2', 'Voucher = stored balance → VAL-0008'), 'warning', 'triangle-alert'); requestRender(); });
onAct('s-refund-confirm', (d) => { const t = S.tickets[d.id]; const o = ord(t.orderId); refundConfirm(o); ticketLog(t, 'finance', L('وصل للعميل', 'Received'), 'status'); requestRender(); });
onAct('s-status', (d) => { const t = S.tickets[d.id]; if (d.v === 'resolved' && !(t.log.some((x) => x.who === 'support' && x.kind === 'msg'))) { toast(L('ما ينفعش تقفلها من غير رد مسبّب للعميل', 'Reply to the customer with a reason first'), 'warning', 'message-circle'); requestRender(); return; } t.status = d.v; t.resolution = d.v === 'resolved' ? L('اتحلّت برد مسبّب', 'Resolved with a reason') : t.resolution; ticketLog(t, 'support', ticketStatusLabel(d.v), 'status'); requestRender(); });
onAct('s-escalate', (d) => { const t = S.tickets[d.id]; ticketLog(t, 'support', L('اتصعّدت للمؤسس', 'Escalated to the founder'), 'status'); notify('admin', { title: L(`تصعيد ${t.id}`, `Escalation ${t.id}`), icon: 'arrow-up-down', silent: userRole() !== 'admin' }); toast(L('اتصعّدت — المؤسس هو الوحيد اللي يعتمد النهارده', 'Escalated — only the founder approves today'), 'info', 'arrow-up-down'); requestRender(); });

/* ================================================================== OPERATIONS */
function opsCenter() {
  const all = Object.values(S.orders); const act = all.filter(isActive);
  const incidents = all.filter((o) => o.pending.some((a) => a.role === 'ops') || o.gate || (o.cnd && isActive(o)));
  const late = act.filter((o) => o.lateFlag || o.lateNotified);
  const views = [{ id: 'live', icon: 'radar', label: L('الطلبات الحية', 'Live orders'), badge: act.length || '' }, { id: 'incidents', icon: 'triangle-alert', label: L('مشاكل مفتوحة', 'Open incidents'), badge: incidents.length || '' }, { id: 'map', icon: 'map', label: L('الخريطة', 'Map') }, { id: 'people', icon: 'users', label: L('المتاجر والكباتن', 'Stores & captains') }, { id: 'log', icon: 'notebook-pen', label: L('سجل فشل التسليم', 'Failed-delivery log') }, { id: 'blocked', icon: 'lock', label: L('خدمات محجوبة', 'Blocked services') }];
  const v = S.nav.ops.view; let main = '';
  if (v === 'live') {
    const cols = [['placed', L('جديد', 'New')], ['accepted', L('اتقبل', 'Accepted')], ['preparing', L('بيتحضّر', 'Preparing')], ['ready', L('جاهز', 'Ready')], ['in_transit', L('في الطريق', 'On the way')]];
    main = `${deskHead(L('مركز العمليات', 'Operations center'), `${act.length} ${L('طلب شغال', 'active')} · ${late.length} ${L('متأخر', 'late')} · ${act.filter((o) => !o.kid && ['accepted', 'preparing', 'ready'].includes(o.st)).length} ${L('من غير كابتن', 'unassigned')}`, btn(L('وضع الطوارئ', 'Emergency mode'), 'ops-outage', { kind: 'danger-ghost', size: 'sm', icon: 'server-crash' }))}
      ${AA('o-transitions-log', 'o-outage-runbook')}
      <div class="kanban">${cols.map(([st, lbl]) => { const list = act.filter((o) => (st === 'in_transit' ? ['picked_up', 'in_transit', 'reattempt'].includes(o.st) : o.st === st)); return `<section class="kcol"><h3>${lbl} <span class="count">${list.length}</span></h3>${list.map((o) => `<button type="button" class="kcard ${o.cnd || o.lateFlag ? 'is-alert' : ''}" data-act="ops-open" data-id="${o.id}"><b dir="ltr" class="num">${o.id}</b><small>${esc(mName(o.mid))}</small><small>${o.kid ? ic('bike', 12) + ' ' + esc(kName(o.kid)) : `<span class="warn-t">${L('من غير كابتن', 'No captain')}</span>`}</small>${o.cnd ? `<span class="pill pill-danger">${L('تعذّر تسليم', 'Cannot deliver')}</span>` : o.lateFlag ? `<span class="pill pill-warning">${L('متأخر', 'Late')}</span>` : ''}</button>`).join('') || `<p class="muted small">—</p>`}</section>`; }).join('')}</div>
      ${S.nav.ops.sel ? opsOrderDetail(ord(S.nav.ops.sel)) : ''}`;
  } else if (v === 'incidents') {
    main = `${deskHead(L('مشاكل مفتوحة', 'Open incidents'), L('كل مشكلة ليها قرار وإخطار — مفيش طلب يتساب معلّق.', 'Every incident gets a decision and a notice.'))}${incidents.length ? incidents.map((o) => opsOrderDetail(o)).join('') : empty(`<div class="big-ic tone-success">${ic('circle-check', 40)}</div>`, L('مفيش مشاكل مفتوحة', 'No open incidents'), L('جرّب «اختبر مشكلة» من لوحة المحاكاة.', 'Try “Inject a problem”.'))}`;
  } else if (v === 'map') {
    const markers = Object.values(MERCHANTS).filter((m) => !m.blocked).map((m) => { const n = MAP.nodes[m.node]; return { x: n.x, y: n.y, kind: 'merchant' }; });
    act.forEach((o) => { const n = MAP.nodes[addrOf(o).node]; markers.push({ x: n.x, y: n.y, kind: 'home' }); });
    const legs = act.filter((o) => o.cap && o.cap.pts).map((o) => ({ pts: o.cap.pts, done: o.cap.dist / o.cap.len }));
    main = `${deskHead(L('خريطة التشغيل', 'Operations map'), L('خريطة توضيحية — مش حقيقية', 'Illustrative map'))}<div class="map-box map-ops">${MAP.render({ legs, markers, fit: [{ x: 60, y: 60 }, { x: 960, y: 1280 }], aspect: 1.6, pad: 20 })}${Object.values(S.captains).map(() => '').join('')}</div>
      <div class="cap-list">${Object.keys(S.captains).map((k) => { const c = S.captains[k]; return `<div class="card cap-li"><span class="avatar" style="--av:${K(k).color}">${esc(kName(k).slice(0, 1))}</span><div><b>${esc(kName(k))}</b><small>${{ online: L('متاح', 'Online'), on_trip: L('في رحلة', 'On trip'), offline: L('مش متاح', 'Offline') }[c.status]} · ${L('عهدة', 'custody')} ${money(c.custody)}</small></div></div>`; }).join('')}</div>`;
  } else if (v === 'people') {
    main = `${deskHead(L('المتاجر والكباتن', 'Stores & captains'), '')}<section class="card"><table class="tbl"><thead><tr><th>${L('المتجر', 'Store')}</th><th>${L('الحالة', 'Status')}</th><th>${L('طلبات شغالة', 'Active')}</th></tr></thead><tbody>${Object.values(MERCHANTS).map((m) => `<tr><td>${esc(mName(m.id))}</td><td>${m.blocked ? truth('notbuilt', { label: L('محجوب', 'Blocked') }) : stPillStore(S.merchants[m.id].status)}</td><td class="num">${act.filter((o) => o.mid === m.id).length}</td></tr>`).join('')}</tbody></table></section>
      <section class="card"><table class="tbl"><thead><tr><th>${L('الكابتن', 'Captain')}</th><th>${L('الحالة', 'Status')}</th><th>${L('رحلات', 'Trips')}</th><th>${L('عهدة', 'Custody')}</th></tr></thead><tbody>${Object.keys(S.captains).map((k) => `<tr><td>${esc(kName(k))}</td><td>${{ online: L('متاح', 'Online'), on_trip: L('في رحلة', 'On trip'), offline: L('مش متاح', 'Offline') }[S.captains[k].status]}</td><td class="num">${S.captains[k].trips}</td><td class="num">${money(S.captains[k].custody)}</td></tr>`).join('')}</tbody></table>${note(L('مفيش عمود «معدل قبول» — وده مقصود.', 'No “acceptance rate” column — on purpose.'), { icon: 'shield-check' })}</section>`;
  } else if (v === 'log') {
    const failed = all.filter((o) => o.cnd || o.label === 'failed_delivery_tag' || o.st === 'failed_delivery');
    main = `${deskHead(L('سجل فشل التسليم (يدوي)', 'Failed-delivery log (manual)'), L('السجل ده مش موجود في النظام — الدليل بيقول يبدأ بدفتر من أول يوم.', 'This log does not exist in the system — the manual says start a notebook on day one.'))}${truth('solution')} ${truth('notbuilt')}${AA('o-manual-log', 'o-no-failed-state')}
      <table class="tbl"><thead><tr><th>${L('الطلب', 'Order')}</th><th>${L('الوقت', 'Time')}</th><th>${L('محاولات', 'Calls')}</th><th>${L('الفرضية', 'Hypothesis')}</th><th>${L('الفئة', 'Category')}</th><th>${L('مصير البضاعة', 'Goods fate')}</th><th>${L('القرار ومين', 'Decision & by')}</th></tr></thead><tbody>${failed.map((o) => `<tr><td dir="ltr">${o.id}</td><td>${o.cnd ? clockStr(o.cnd.at) : '—'}</td><td class="num">${(o.calls || []).length + ((o.cnd && o.cnd.calls) || []).length}</td><td>${o.cnd && o.cnd.hypo ? esc(HYPOS.find((h) => h.id === o.cnd.hypo).ar) : `<span class="warn-t">${L('ما اتسجلتش', 'Not recorded')}</span>`}</td><td>${L('أكل محضّر', 'Prepared food')}</td><td>${o.fate && o.fate.status === 'simulated' ? `${truth('sim')}` : `<span class="err-t">${L('غير محسوم', 'Undecided')}</span>`}</td><td>${o.label ? L('إلغاء عمليات موسوم', 'Tagged ops cancel') : '—'}</td></tr>`).join('') || `<tr><td colspan="7" class="muted">${L('لسه مفيش', 'None yet')}</td></tr>`}</tbody></table>`;
  } else {
    main = `${deskHead(L('خدمات محجوبة', 'Blocked services'), L('ما يتشغلش قبل التجربة (60.2).', 'Not to be run before the pilot.'))}<div class="stack-12">${[['OPS_003', L('الطلب متعدد المتاجر', 'Multi-store orders'), 'split'], ['OPS_004', L('الطلب المجدول والمناسبات', 'Scheduled & occasion orders'), 'calendar-clock'], ['PHARM_001', L('الصيدلة وأي فئة دوائية', 'Pharmacy'), 'pill'], ['RISK_003', L('أي تقييد تلقائي لعميل أو تاجر أو كابتن', 'Any automatic restriction'), 'lock'], ['CAPTAIN_006', L('أي خصم من مستحق كابتن', 'Any deduction from captain earnings'), 'hand-coins'], ['CAPTAIN_003', L('أي قياس لمعدل قبول الكابتن أو ساعاته', 'Any acceptance/hours measurement'), 'gauge']].map(([p, t, i]) => `<div class="card blocked-row"><span class="row-ic">${ic(i, 20)}</span><div class="grow"><b>${t}</b><div class="chips-row">${truth('notbuilt', { label: L('محجوب', 'Blocked') })}${P(p)}</div></div></div>`).join('')}${AA('o-multistore-blocked', 'o-scheduled-blocked')}</div>`;
  }
  return deskFrame('ops', views, main, { who: L(`${PEOPLE.ops.name} — العمليات`, 'Karim — Operations') });
}
function opsOrderDetail(o) {
  if (!o) return '';
  const pend = o.pending.filter((a) => a.role === 'ops');
  const steps = [
    [L('استقبال التصعيد من الكابتن', 'Receive the captain’s escalation'), !!o.cnd],
    [L('اتصال مستقل من رقم تاني (إلزامي)', 'Independent call from another number (mandatory)'), !!(o.cnd && o.cnd.calls && o.cnd.calls.length)],
    [L('قراءة سجل الانتقالات: فيه تأخير جسيم؟', 'Read the transitions log: severe delay?'), !!(o.cnd && o.cnd.hypo)],
    [L('تسجيل الفرضية الأقرب من الخمسة', 'Record the closest of five hypotheses'), !!(o.cnd && o.cnd.hypo)],
    [L('قرار مصير البضاعة حسب الفئة', 'Decide the goods’ fate by category'), !!(o.fate)],
    [L('إغلاق الطلب (إلغاء عمليات موسوم «فشل تسليم»)', 'Close the order (tagged ops cancel)'), o.st === 'cancelled' || o.st === 'failed_delivery'],
    [L('إبلاغ العميل: مفيش أي مبلغ مستحق عليه', 'Tell the customer they owe nothing'), o.st === 'cancelled' || o.st === 'failed_delivery'],
    [L('تسجيل الواقعة في سجل فشل التسليم', 'Log it in the failed-delivery log'), false],
  ];
  const delay = o.stAt.ready && o.stAt.preparing ? (o.stAt.ready - o.stAt.preparing) - o.prep : 0;
  return `<article class="card ops-inc stack-12"><header class="row-between"><div><h2><bdi dir="ltr">${o.id}</bdi> · ${esc(mName(o.mid))}</h2><p class="muted">${stPill(o.st)} ${o.kid ? `· ${L('الكابتن', 'Captain')} ${esc(kName(o.kid))}` : ''} ${o.cnd ? `· ${reasonLabel(o.cnd.reason)}` : ''}</p></div>${iconBtn('x', L('إغلاق', 'Close'), 'ops-close-detail')}</header>
    ${o.cnd ? `<section>${sectionHead(L('خطوات فشل التسليم (53.2)', 'Failed-delivery steps (53.2)'), { icon: 'list-checks' })}<ol class="checklist">${steps.map(([t, done]) => `<li class="${done ? 'done' : ''}">${ic(done ? 'square-check' : 'square', 16)}<span>${t}</span></li>`).join('')}</ol>${AA('o-independent-call', 'o-five-hypotheses')}</section>` : ''}
    ${pend.some((a) => a.kind === 'o_call') ? `<div class="stack-8"><b>${L('اتصل بالعميل من رقم تاني', 'Call the customer from another number')}</b>${msgQuote(o.cnd && o.cnd.reason === 'no_answer' ? 'MSG-C-003' : 'MSG-C-004')}${btn(L('اتصل (محاكاة)', 'Call (simulated)'), 'ops-call', { icon: 'phone-call', data: { id: o.id } })}</div>` : ''}
    ${pend.some((a) => a.kind === 'o_hypo') ? `<div class="stack-8"><b>${L('سجل الانتقالات يقول:', 'The transitions log says:')}</b> <span>${delay > 10 ? `<span class="warn-t">${L(`تأخير ${Math.round(delay)} دقيقة عند المتجر`, `${Math.round(delay)} min store delay`)}</span>` : L('مفيش تأخير جسيم مسجّل', 'No severe delay recorded')}</span><b>${L('اختار الفرضية (الأقل إدانة للعميل لحد ما تتميّز):', 'Pick the hypothesis (least blaming until distinguished):')}</b><div class="stack-8">${HYPOS.map((h) => `<button type="button" class="rcard" data-act="ops-hypo" data-id="${o.id}" data-v="${h.id}"><span class="rcard-main"><span class="rcard-title">${L(h.ar, h.en)}</span><span class="rcard-sub">${esc(h.note)}</span></span></button>`).join('')}</div></div>` : ''}
    ${o.gate ? `<section class="gate stack-8"><div class="truth-row">${truth('decision')}${truth('finance')}${truth('legal')}</div><h3 class="h-sm">${L('ماذا يحدث للطلب والبضاعة والمال؟', 'What happens to the order, goods and money?')}</h3><p>${L('مفيش قاعدة في أي مكان (FDR-0001). وتعويض الكابتن كمان مش محسوم (FDR-0002). المحاكي ما بيختارش نيابة عنك.', 'No rule exists (FDR-0001), captain compensation undecided (FDR-0002). The simulator won’t choose for you.')}</p>
      <div class="stack-8">${btn(L('قارن الحلول', 'Compare solutions'), 'compare-open', { icon: 'split', data: { fdr: 'FDR-0001', id: o.id } })}${btn(L('اللي بيتعمل النهارده: إلغاء عمليات موسوم', 'Today’s workaround: tagged ops cancel'), 'ops-tagcancel', { kind: 'secondary', data: { id: o.id } })}${btn(L('سيبه معلّق (ده اللي بيحصل من غير قرار)', 'Leave it hanging (what happens without a decision)'), 'ops-leave', { kind: 'ghost', data: { id: o.id } })}</div>${AA('o-no-failed-state', 'k-failed-trip-pay')}</section>` : ''}
    ${pend.some((a) => a.kind === 'o_change') ? `<div class="stack-8"><b>${L('مشكلة فكة — المنصّة مسؤولة', 'Change problem — platform’s responsibility')}</b>${msgQuote('MSG-K-002')}<div class="stack-8">${btn(L('ابعت فكة مع كابتن قريب', 'Send change via a nearby captain'), 'ops-change', { data: { id: o.id, v: 'captain2' } })}${btn(L('العميل يفك من محل جنبه (اختياري ليه)', 'Customer breaks the note nearby (optional)'), 'ops-change', { kind: 'secondary', data: { id: o.id, v: 'shop' } })}${btn(L('«ائتمان فكة» على المنصّة', '“Change credit” on the platform'), 'ops-change', { kind: 'ghost', data: { id: o.id, v: 'credit' } })}</div>${AA('c-change-prompt')}</div>` : ''}
    ${pend.some((a) => a.kind === 'o_transfer') ? `<div class="stack-8"><b>${L('الكابتن واقف والأكل معاه', 'Captain stopped with the food')}</b>${msgQuote('MSG-K-004')}${btn(L('انقل الطلب لكابتن تاني', 'Hand over to another captain'), 'ops-transfer', { data: { id: o.id } })}${AA('k-breakdown-handoff')}</div>` : ''}
    ${o.cnd && o.cnd.words ? `<p class="muted small">${ic('lock', 12)}${L('كلام العميل متسجل عند العمليات بس — ما يتشاركش مع التاجر ولا الكابتن.', 'Customer’s words stay with ops.')}</p>` : ''}
    <details><summary>${L('سجل الانتقالات', 'Transitions log')}</summary>${tlList(o, 'ops')}</details>
    <div class="chips-row">${P('OPS_002')}${P('CUSTOMER_003')}${P('OPS_001')}</div></article>`;
}
onAct('ops-open', (d) => { S.nav.ops.sel = d.id; requestRender(); });
onAct('ops-close-detail', () => { S.nav.ops.sel = null; requestRender(); });
onAct('ops-call', (d) => { const o = ord(d.id); S.busy.opsCall = true; requestRender(); setTimeout(() => { S.busy.opsCall = false; opsIndependentCall(o); requestRender(); }, 900); });
onAct('ops-hypo', (d) => { opsSetHypothesis(ord(d.id), d.v); requestRender(); });
onAct('ops-tagcancel', (d) => { S.dialog = { title: L('إلغاء عمليات موسوم «فشل تسليم»؟', 'Tagged ops cancellation?'), body: L('ده الحل المؤقت اللي الدليل بيسمح بيه: الطلب يتقفل كإلغاء، ويتوسم إنه فشل تسليم، والعميل يتبلّغ إنه مش مدين بحاجة. العمولة والتسوية والتقارير هتتلخبط، ومصير الأكل وتعويض الكابتن يفضلوا مش محسومين.', 'The manual’s workaround. Commission, settlement and reports get distorted; goods fate and captain pay stay undecided.'), confirm: { label: L('نفّذ الحل المؤقت', 'Apply workaround'), act: 'ops-tagcancel-do', data: { id: d.id } }, anno: 'o-no-failed-state' }; requestRender(); });
onAct('ops-tagcancel-do', (d) => { const id = (S.dialog && S.dialog.confirm && S.dialog.confirm.data && S.dialog.confirm.data.id) || d.id; S.dialog = null; opsCloseAsTaggedCancel(ord(id)); requestRender(); });
onAct('ops-leave', (d) => { const o = ord(d.id); tl(o, { ev: 'left', actor: 'ops', note: L('الطلب متساب معلّق — «في الطريق» بلا نهاية (CFL-0004)', 'Left hanging — “on the way” forever (CFL-0004)'), kind: 'warn' }); toast(L('ده بالظبط اللي بيحصل من غير قرار: الطلب «في الطريق» بلا نهاية', 'This is what happens without a decision'), 'warning', 'hourglass'); requestRender(); });
onAct('ops-change', (d) => { SCN_RUNTIME.changeFix(ord(d.id), d.v); requestRender(); });
onAct('ops-transfer', (d) => { SCN_RUNTIME.transfer(ord(d.id)); requestRender(); });
onAct('ops-outage', () => { SCN_RUNTIME.outage(true); requestRender(); });
onAct('ops-restore', () => { SCN_RUNTIME.outage(false); requestRender(); });

/* ================================================================== FINANCE */
function financeDesk() {
  const all = Object.values(S.orders);
  const views = [{ id: 'orders', icon: 'receipt-text', label: L('دفتر الطلبات', 'Order ledger') }, { id: 'recon', icon: 'scale', label: L('مطابقة الكاش', 'Cash reconciliation') }, { id: 'refunds', icon: 'hand-coins', label: L('الاستردادات', 'Refunds') }, { id: 'model', icon: 'calculator', label: L('نموذج المسؤولية', 'Liability model') }];
  const v = S.nav.finance.view; let main = '';
  if (v === 'orders') {
    main = `${deskHead(L('دفتر الطلبات', 'Order ledger'), L('كل رقم عليه علامة: مثال توضيحي / قيمة في الكود مش معتمدة / فعلي في المحاكاة.', 'Every number is labelled.'))}
      <div class="legend">${truth('sim', { label: L('فعلي في المحاكاة', 'Actual in simulation') })}${truth('finance', { label: L('قيمة في الكود — مش معتمدة', 'Code value — not approved') })}${truth('unknown', { label: L('مثال توضيحي', 'Illustrative') })}${truth('decision', { label: L('غير محسوم', 'Undecided') })}</div>${AA('f-commission-unknown', 'f-principal-agent')}
      <div class="tbl-wrap"><table class="tbl tbl-fin"><thead><tr><th>${L('الطلب', 'Order')}</th><th>${L('الحالة', 'Status')}</th><th>${L('العميل دفع', 'Customer paid')}</th><th>${L('للتاجر', 'Merchant')}</th><th>${L('توصيل', 'Delivery')}</th><th>${L('للكابتن', 'Captain')}</th><th>${L('لوصّلي', 'Wasaly')}</th><th>${L('كاش مع الكابتن', 'Cash held')}</th><th>${L('استرداد', 'Refund')}</th><th>${L('خسارة', 'Loss')}</th><th>${L('التسوية', 'Settlement')}</th></tr></thead><tbody>${all.map((o) => { const mo = moneyOf(o); const del = ['delivered', 'completed'].includes(o.st); return `<tr><td dir="ltr">${o.id}</td><td>${stPill(o.st)}</td><td class="num">${money(mo.customerPaid)}</td><td class="num">${del ? money(mo.merchantNet) : o.cnd || o.label ? `<span class="err-t">${L('غير محسوم', 'Undecided')}</span>` : '—'}</td><td class="num">${money(o.del)}</td><td class="num">${del ? money(mo.share) : o.cnd || o.label ? `<span class="err-t">${L('0 — غير محسوم', '0 — undecided')}</span>` : '—'}</td><td class="num">${del ? money(mo.wasalyRev) : L('ما نشأش', 'Not generated')}</td><td class="num">${money(mo.captainHolds)}</td><td class="num">${o.refund ? `${money(o.refund.amount)} <small>${o.refund.stage}</small>` : '—'}</td><td class="num">${mo.expectedLoss ? `${money(mo.expectedLoss)} <small>${L('مشوار — مثال', 'trip — illustrative')}</small>${mo.goods ? `<br><small>${L('+ الأكل', '+ food')} ${money(mo.goods.amount)}: ${goodsBearer(mo.goods.bearer)}</small>` : ''}` : '—'}</td><td>${del ? `${L('مستحق بعد', 'Due in')} ${ECON.settlementHours}${L('س', 'h')}` : '—'}</td></tr>`; }).join('') || `<tr><td colspan="11" class="muted">${L('مفيش طلبات — ابدأ سيناريو', 'No orders — start a scenario')}</td></tr>`}</tbody></table></div>
      ${note(L('العمولة عن طلب ما اتسلّمش «ما نشأتش» — مش خسارة. والرد للعميل + الخصم من التاجر = عملية واحدة مش خسارتين.', 'Commission on an undelivered order was never generated — not a loss.'))}${AA('f-not-generated-not-loss', 'f-one-transfer-not-two')}`;
  } else if (v === 'recon') {
    main = `${deskHead(L('مطابقة كاش الكباتن', 'Captain cash reconciliation'), L('يومية: المحصَّل مقابل المورَّد.', 'Daily: collected vs deposited.'))}${Object.keys(S.captains).map((k) => { const c = S.captains[k]; return `<section class="card stack-8"><div class="row-between"><b>${esc(kName(k))}</b><span class="num">${L('عهدة حالية', 'Current custody')} ${money(c.custody)}</span></div>${c.deposits.length ? `<table class="tbl"><thead><tr><th>${L('الوقت', 'Time')}</th><th>${L('متوقع', 'Expected')}</th><th>${L('فعلي', 'Actual')}</th><th>${L('فرق', 'Difference')}</th><th>${L('الإجراء', 'Action')}</th></tr></thead><tbody>${c.deposits.map((dp, i) => `<tr><td>${clockStr(dp.t)}</td><td class="num">${money(dp.expected)}</td><td class="num">${money(dp.actual)}</td><td class="num">${dp.diff ? `<span class="warn-t">${money(dp.diff)}</span>` : '—'}</td><td>${dp.diff ? `${btn(L('إعدام الفرق', 'Write off'), 'f-writeoff', { kind: 'ghost', size: 'sm', data: { k, i } })} ${btn(L('خصم من الكابتن', 'Deduct from captain'), 'f-deduct', { kind: 'ghost', size: 'sm', data: { k, i } })}` : truth('current', { label: L('مطابق', 'Matched') })}</td></tr>`).join('')}</tbody></table>` : `<p class="muted">${L('مفيش توريدات لسه.', 'No deposits yet.')}</p>`}</section>`; }).join('')}${AA('f-custody-not-wallet', 'f-writeoff-prohibited', 'k-cash-diff')}`;
  } else if (v === 'refunds') {
    const rfs = all.filter((o) => o.refund);
    main = `${deskHead(L('الاستردادات', 'Refunds'), L('المعتمد مقابل المنفّذ — الفرق بينهم مؤشر خطر مباشر.', 'Approved vs executed.'))}<table class="tbl"><thead><tr><th>${L('الطلب', 'Order')}</th><th>${L('المبلغ', 'Amount')}</th><th>${L('المرحلة', 'Stage')}</th><th>${L('الطريقة', 'Route')}</th><th>${L('اعتمده', 'Approved by')}</th></tr></thead><tbody>${rfs.map((o) => `<tr><td dir="ltr">${o.id}</td><td class="num">${money(o.refund.amount)}</td><td>${o.refund.stage}</td><td>${o.refund.route ? routeLabel(o.refund.route) + (o.refund.route === 'voucher' ? ' ' + truth('problem', { label: L('يخالف 12-2', 'conflicts 12-2') }) : '') : '—'}</td><td>${o.refund.approver ? actorLabel(o.refund.approver) : '—'}</td></tr>`).join('') || `<tr><td colspan="5" class="muted">${L('مفيش', 'None')}</td></tr>`}</tbody></table>${AA('f-refund-approval', 'f-voucher-liability')}`;
  } else {
    main = `${deskHead(L('نموذج المسؤولية المالية — 6 أسئلة', 'Financial liability model — 6 questions'), L('«المخطئ يدفع» مش سياسة: دي 6 قرارات منفصلة.', '“The one at fault pays” hides six decisions.'))}
      <table class="tbl"><thead><tr><th>#</th><th>${L('السؤال', 'Question')}</th><th>${L('طبيعته', 'Nature')}</th><th>${L('مين يجاوب', 'Who answers')}</th></tr></thead><tbody>${[['من دفع أولًا؟', 'واقعة', 'المالية'], ['من تحمّل الكلفة مؤقتًا؟', 'واقعة — المنصّة في الغالب', 'المالية'], ['من تسبّب؟', 'استنتاج من دليل', 'العمليات'], ['هل الكلفة قابلة للاسترداد أصلًا؟', 'سؤال سند', 'المحامي'], ['هل استُردت فعلًا؟', 'واقعة لاحقة', 'المالية'], ['ما القيد المحاسبي؟', 'معالجة', 'المحاسب']].map((r, i) => `<tr><td class="num">${i + 1}</td><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table>
      <section class="card stack-8">${sectionHead(L('جدول مرجعي سريع', 'Quick reference'), { icon: 'table' })}<table class="tbl"><thead><tr><th>${L('الواقعة', 'Event')}</th><th>${L('تمويل مؤقت', 'Temp funding')}</th><th>${L('التحميل النهائي', 'Final')}</th></tr></thead><tbody>${[['فشل تسليم — سبب غير محدد', 'المنصّة', 'غير محسوم'], ['فشل تسليم — تأخير التاجر بدليل', 'المنصّة', 'التاجر بعد الإثبات'], ['تعذّر الفكّة', 'المنصّة', 'المنصّة — ولا تحميل على أحد'], ['نقص أو صنف خاطئ', 'المنصّة', 'يُبحث بعد علاج العميل'], ['فرق نقد', 'المنصّة', 'لا تحميل على الكابتن']].map((r) => `<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2].startsWith('غير') ? `<span class="err-t">${r[2]}</span>` : r[2]}</td></tr>`).join('')}</tbody></table>${AA('f-principal-agent')}</section><div class="chips-row">${P('FIN_007')}${P('FIN_006')}${P('FIN_009')}</div>`;
  }
  return deskFrame('finance', views, main, { who: L(`${PEOPLE.finance.name} — المالية`, 'Hala — Finance') });
}
onAct('f-writeoff', () => { S.dialog = { title: L('إعدام الفرق؟', 'Write off the difference?'), body: L('الإعدام محظور لحد ما يبقى فيه شخص تاني يعتمد (AUT-0006) — واللي عدّ الفلوس ما يعتمدش الإعدام. وحد الإعدام نفسه (PAR-0021) مش محدد. المحاكي مش هينفّذه.', 'Prohibited until a second person exists (AUT-0006). Threshold undecided (PAR-0021). Not executed.'), confirm: { label: L('فهمت', 'Understood'), act: 'dialog-close' }, anno: 'f-writeoff-prohibited', tone: 'danger' }; requestRender(); });
onAct('f-deduct', () => { S.dialog = { title: L('خصم من الكابتن؟', 'Deduct from the captain?'), body: L('ممنوع: مفيش خصم ولا حجز من مستحق كابتن قبل رأي المحامي في جواز المقاصّة أصلًا (VAL-0011). والفرق وحده ما بيثبتش دين.', 'Forbidden before counsel answers VAL-0011.'), confirm: { label: L('فهمت', 'Understood'), act: 'dialog-close' }, anno: 'k-cash-diff', tone: 'danger' }; requestRender(); });

/* ================================================================== ADMIN */
const FLAGS = [
  { k: 'multiStore', ar: 'الطلب متعدد المتاجر', en: 'Multi-store orders', pol: 'OPS_003', risk: 'high', note: 'محجوب — بنية الطلبات الفرعية غير محقَّقة.' },
  { k: 'scheduled', ar: 'الطلب المجدول والمناسبات', en: 'Scheduled orders', pol: 'OPS_004', risk: 'high', note: 'محجوب — مفيش طاقة تتحجز.' },
  { k: 'pharmacy', ar: 'قسم الصيدليات', en: 'Pharmacy category', pol: 'PHARM_001', risk: 'critical', note: 'محجوب لحد FDR-0009 ورأي صيدلي ومحامي.' },
  { k: 'cardPay', ar: 'الدفع بالبطاقة', en: 'Card payments', pol: 'FIN_002', risk: 'high', note: 'غير مبني.' },
  { k: 'balance', ar: 'رصيد العميل / المحفظة', en: 'Customer balance / wallet', pol: 'LEGAL_004', risk: 'critical', note: 'محجوب لحد FDR-0010 و VAL-0008.' },
  { k: 'acceptanceTracking', ar: 'قياس معدل قبول الكابتن', en: 'Captain acceptance tracking', pol: 'CAPTAIN_003', risk: 'critical', note: 'ممنوع قبل حسم FDR-0004 ورأي المحامي — بناؤه يزيد التعرّض القانوني.' },
  { k: 'autoRestrict', ar: 'تقييد تلقائي للحسابات', en: 'Automatic account restriction', pol: 'RISK_003', risk: 'critical', note: 'ممنوع — لازم قرار بشري + إخطار + تظلّم.' },
  { k: 'failedState', ar: 'حالة «فشل تسليم» (مقترحة)', en: '“Failed delivery” state (proposed)', pol: 'OPS_002', risk: 'medium', note: 'حل مقترح — غير مبني.' },
  { k: 'maskedCalls', ar: 'أرقام وسيطة للمكالمات', en: 'Masked phone numbers', pol: 'DATA_002', risk: 'medium', note: 'غير متحقق إنه مبني.' },
];
function adminDesk() {
  const views = [{ id: 'flags', icon: 'sliders-horizontal', label: L('المزايا', 'Feature flags') }, { id: 'values', icon: 'calculator', label: L('قيم حساسة', 'Sensitive values') }, { id: 'catalog', icon: 'layout-grid', label: L('الأقسام والمتاجر', 'Categories & stores') }, { id: 'areas', icon: 'map', label: L('مناطق الخدمة', 'Service areas') }, { id: 'roles', icon: 'key-round', label: L('الصلاحيات', 'Permissions') }, { id: 'audit', icon: 'scroll-text', label: L('سجل التدقيق', 'Audit log') }];
  const v = S.nav.admin.view; let main = '';
  if (v === 'flags') {
    main = `${deskHead(L('المزايا', 'Feature flags'), L('كل تغيير خطير محتاج تأكيد + سبب + يتسجل في سجل التدقيق.', 'Every risky change needs confirmation, a reason and an audit entry.'))}${truth('sim', { label: L('المزايا هنا محاكاة — المزايا الحقيقية غير معروفة', 'Flags here are simulated') })}${AA('a-feature-flags', 'a-acceptance-flag')}
      <div class="stack-8">${FLAGS.map((f) => `<div class="card flag-row"><div class="grow"><b>${L(f.ar, f.en)}</b><small>${esc(f.note)}</small><div class="chips-row">${P(f.pol)}<span class="pill pill-${f.risk === 'critical' ? 'danger' : f.risk === 'high' ? 'warning' : 'info'}">${{ critical: L('خطر حرج', 'Critical'), high: L('خطر مرتفع', 'High'), medium: L('متوسط', 'Medium') }[f.risk]}</span></div></div>${toggle(S.flags[f.k], 'a-flag', L(f.ar, f.en), { data: { k: f.k } })}</div>`).join('')}</div>`;
  } else if (v === 'values') {
    const vals = [['PAR-0006', L('مهلة تسوية التاجر', 'Merchant settlement window'), `${ECON.settlementHours} ${L('ساعة', 'h')}`], ['PAR-0007', L('غرامة تأخر التسوية يوميًا', 'Daily settlement penalty'), `${ECON.penaltyPct}%`], ['PAR-0008', L('أيام السماح', 'Grace days'), ECON.graceDays], ['PAR-0009', L('حد أقصى للغرامة', 'Penalty cap'), `${ECON.penaltyMaxPct}%`], ['PAR-0010', L('حصة الكابتن من التوصيل', 'Captain share of delivery'), `${ECON.captainSharePct}%`], ['PAR-0013', L('حد العهدة اليومية', 'Daily custody limit'), money(ECON.custodyLimit)], ['PAR-0023', L('رسوم الخدمة', 'Service fee'), money(ECON.serviceFee)], ['PAR-0025', L('نافذة النزاع', 'Dispute window'), `${ECON.disputeHours} ${L('ساعة', 'h')}`], ['PAR-0011', L('عتبة القبول في الاتفاقية', 'Contract acceptance threshold'), '80%'], ['PAR-0012', L('الضمان الشهري', 'Monthly guarantee'), money(5000)], ['PAR-0003', L('تعويض الرحلة الفاشلة', 'Failed-trip compensation'), money(0)], ['PAR-0004', L('حد صلاحية الاسترداد', 'Refund authority limit'), L('غير محدد', 'Not set')]];
    main = `${deskHead(L('قيم حساسة', 'Sensitive values'), L('«قيمة قائمة في النظام» ≠ «قيمة معتمدة».', '“Value in the system” ≠ “approved value”.'))}${AA('a-values-unapproved', 'a-id-conflict')}<table class="tbl"><thead><tr><th>${L('المعرّف', 'ID')}</th><th>${L('المتغير', 'Variable')}</th><th>${L('القيمة', 'Value')}</th><th>${L('الحالة', 'Status')}</th><th></th></tr></thead><tbody>${vals.map((r) => `<tr><td dir="ltr">${r[0]}</td><td>${r[1]}</td><td class="num">${r[2]}</td><td>${MANUAL.par[r[0]] && MANUAL.par[r[0]].status.includes('غير محدد') ? truth('decision', { label: L('غير محدد', 'Not set') }) : truth('finance', { label: L('في الكود — مش معتمدة', 'In code — not approved') })}</td><td>${btn(L('غيّر', 'Change'), 'a-value', { kind: 'ghost', size: 'sm', data: { id: r[0] } })}</td></tr>`).join('')}</tbody></table>`;
  } else if (v === 'catalog') {
    main = `${deskHead(L('الأقسام والمتاجر', 'Categories & stores'), '')}<section class="card"><table class="tbl"><thead><tr><th>${L('القسم', 'Category')}</th><th>${L('الحالة', 'Status')}</th></tr></thead><tbody>${CATEGORIES.map((c) => `<tr><td>${catName(c)}</td><td>${c.blocked ? truth('notbuilt', { label: L('محجوب', 'Blocked') }) : truth('current', { label: L('مفعّل (تجريبي)', 'Enabled (demo)') })}</td></tr>`).join('')}</tbody></table>${AA('a-pharmacy-flag')}</section>
      <section class="card"><table class="tbl"><thead><tr><th>${L('المتجر', 'Store')}</th><th>${L('التفعيل', 'Activation')}</th><th>${L('التحقق', 'Verification')}</th></tr></thead><tbody>${Object.values(MERCHANTS).map((m) => `<tr><td>${esc(mName(m.id))}</td><td>${m.blocked ? truth('notbuilt', { label: L('محجوب', 'Blocked') }) : L('مفعّل', 'Active')}</td><td>${truth('sim', { label: L('متجر تجريبي — مش نشاط حقيقي', 'Demo — not a real business') })}</td></tr>`).join('')}</tbody></table></section>`;
  } else if (v === 'areas') {
    main = `${deskHead(L('مناطق الخدمة', 'Service areas'), L('حدود التغطية هنا مثال — مش حدود حقيقية.', 'Coverage here is an example.'))}<div class="map-box map-ops">${MAP.render({ markers: [], fit: [{ x: 60, y: 60 }, { x: 960, y: 1280 }], aspect: 1.6, pad: 20 })}</div>${AA('c-coverage')}`;
  } else if (v === 'roles') {
    main = `${deskHead(L('مصفوفة الصلاحيات', 'Authority matrix'), L('20 صلاحية — ومكتوب بصراحة فين فصل المهام مش موجود.', '20 authorities — and where separation of duties is missing.'))}${AA('a-separation-duties', 'a-permissions-grant')}<div class="tbl-wrap"><table class="tbl"><thead><tr><th>${L('المعرّف', 'ID')}</th><th>${L('الإجراء', 'Action')}</th><th>${L('يعتمد', 'Approves')}</th><th>${L('للمؤسس؟', 'Founder only?')}</th><th>${L('التعارض والضابط', 'Conflict & control')}</th></tr></thead><tbody>${Object.values(MANUAL.aut).map((a) => `<tr class="${a.prohibited ? 'row-danger' : ''}"><td dir="ltr">${a.id}</td><td>${esc(a.action)}</td><td>${esc(a.approve)}</td><td>${a.founderOnly ? L('نعم', 'Yes') : L('لا', 'No')}</td><td><small>${esc(a.conflict)}</small>${a.prohibited ? `<br>${truth('problem', { label: L('محظور لحد ما يبقى فيه شخص تاني', 'Prohibited until a second person') })}` : ''}</td></tr>`).join('')}</tbody></table></div>`;
  } else {
    main = `${deskHead(L('سجل التدقيق', 'Audit log'), L('كل انتقال ليه فاعل وتوقيت — ولا تعديل بأثر رجعي.', 'Every change has an actor and time — no retroactive edits.'))}${AA('a-audit-log')}<table class="tbl"><thead><tr><th>${L('الوقت', 'Time')}</th><th>${L('مين', 'Who')}</th><th>${L('إيه', 'What')}</th><th>${L('التفاصيل', 'Details')}</th></tr></thead><tbody>${S.audit.map((a) => `<tr><td>${clockStr(a.t)}</td><td>${actorLabel(a.who)}</td><td dir="ltr">${esc(a.what)}</td><td>${esc(a.detail || '')}</td></tr>`).join('') || `<tr><td colspan="4" class="muted">${L('فاضي', 'Empty')}</td></tr>`}</tbody></table>`;
  }
  return deskFrame('admin', views, main, { who: L('المؤسس — الإدارة', 'Founder — Admin') });
}
onAct('a-flag', (d) => { const f = FLAGS.find((x) => x.k === d.k); S.dialog = { title: S.flags[d.k] ? L(`إيقاف «${f.ar}»؟`, `Disable “${f.en}”?`) : L(`تفعيل «${f.ar}»؟`, `Enable “${f.en}”?`), body: `${esc(f.note)}${f.risk === 'critical' ? '<br><b>' + L('تغيير حرج: المحاكي هيسجله في سجل التدقيق كتجربة بس — ومش قرار معتمد.', 'Critical change: logged as a simulation only — not an approved decision.') + '</b>' : ''}`, reason: true, confirm: { label: L('أكّد وسجّل', 'Confirm & log'), act: 'a-flag-do', data: { k: d.k } }, tone: f.risk === 'critical' ? 'danger' : undefined }; requestRender(); });
onAct('a-flag-do', () => { const d = S.dialog.confirm.data; if (!(S.dialog.reasonText || '').trim()) { S.dialog.err = L('اكتب السبب — مفيش تغيير حساس من غير سبب مسجل.', 'Enter a reason.'); requestRender(); return; } S.flags[d.k] = !S.flags[d.k]; audit('founder', 'flag.' + d.k, `${S.flags[d.k] ? 'ON' : 'OFF'} — ${S.dialog.reasonText} (simulation)`); S.dialog = null; toast(L('اتسجل في سجل التدقيق (محاكاة)', 'Logged in the audit trail (simulated)'), 'info', 'scroll-text'); requestRender(); });
onAct('a-value', (d) => { S.dialog = { title: L(`تغيير ${d.id}؟`, `Change ${d.id}?`), body: L('تغيير قيمة مالية أو تشغيلية في الإنتاج محجوز للمؤسس (AUT-0012) ومحتاج مراجعة تقنية مستقلة قبل النشر. في المحاكاة التغيير بيتسجل بس.', 'Reserved for the founder (AUT-0012). In the simulation it is only logged.'), reason: true, confirm: { label: L('سجّل طلب التغيير', 'Log change request'), act: 'a-value-do', data: { id: d.id } } }; requestRender(); });
onAct('a-value-do', () => { const d = S.dialog.confirm.data; if (!(S.dialog.reasonText || '').trim()) { S.dialog.err = L('اكتب السبب.', 'Enter a reason.'); requestRender(); return; } audit('founder', 'value.request', `${d.id} — ${S.dialog.reasonText}`); S.dialog = null; toast(L('اتسجل كطلب تغيير — مش قرار معتمد', 'Logged as a request — not an approved decision'), 'info', 'scroll-text'); requestRender(); });
onAct('s-close', () => { S.nav.support.sel = null; requestRender(); });
onAct('desk-view', (d) => { S.nav[d.role].view = d.v; requestRender(); });
